spring.application.name=ADDRESS-SERVICE
server.port=8082
# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=rohan
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate (if using Spring Data JPA)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=address-service

# Eureka Service
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.serviceUrl.defaultZone=http://localhost:8080/eureka
eureka.instance.hostname=localhost

# Kafka Broker Address
spring.kafka.bootstrap-servers=localhost:9092
# Topic name
spring.kafka.topic-employee=employee-topic
# Consumer group id
spring.kafka.consumer.group-id=employee-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
# Enable batch listener
spring.kafka.listener.type=batch
# Max poll records (number of messages per batch)
spring.kafka.consumer.max-poll-records=100
logging.level.com.microservices.address.service.KafkaMessageConsumer=DEBUG

# actuator endpoints
management.endpoints.web.exposure.include=health,prometheus
management.endpoint.health.show-details=always
management.endpoint.metrics.enabled=true
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true

management.tracing.enabled=true
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
